### ISSUE TITLE
Stopped working after 88d473a

### ISSUE THREAD

**Issue by rebelot** [quangnguyen30192/cmp-nvim-ultisnips#25]
as per title, the new parser removed ultisnip completion items from cmp list after 88d473a7385c15b64e9e3fbdeefdd7494d5bc825

neovim version v0.6.0-dev+631-g72d62aa6a

**Comment by smjonas** [comment]
Hey, could you confirm if this is still the case with the latest version? Also, I will create a PR in a few minutes that should resolve some issues with snippets not showing up.

**Comment by rebelot** [comment]
Yes, stopped working right after rebuilding latest neovim and updating plugins

**Comment by smjonas** [comment]
Sorry about that, I should have tested the new parser better. This should be fixed once #26 has been merged.

**Comment by smjonas** [comment]
@quangnguyen30192 thank you for the fast merging, @rebelot could you pull the latest update and test again?

**Comment by rebelot** [comment]
Still not working for me, but thanks for your super quick response!

**Comment by rebelot** [comment]
any update? I'll share my minimal config
```lua
use({
    "SirVer/ultisnips",
    requires = {"honza/vim-snippets", rtp = "."},
    config = function()
	vim.g.UltiSnipsExpandTrigger = "<Plug>(ultisnips_expand)"
	vim.g.UltiSnipsJumpForwardTrigger = "<Plug>(ultisnips_jump_forward)"
	vim.g.UltiSnipsJumpBackwardTrigger = "<Plug>(ultisnips_jump_backward)"
	vim.g.UltiSnipsListSnippets = "<c-x><c-s>"
	vim.g.UltiSnipsRemoveSelectModeMappings = 0
    end,
})

use({
    "hrsh7th/nvim-cmp",
    requires = {"quangnguyen30192/cmp-nvim-ultisnips"},
    config = function()
        local cmp = require('cmp')
            cmp.setup {
                snippet = {
                    expand = function(args) vim.fn["UltiSnips#Anon"](args.body) end
                },
                mapping = {
                    ['<C-Space>'] = cmp.mapping(cmp.mapping.complete(), {'i', 'c'}),
                    ['<CR>'] = cmp.mapping.confirm({ behavior = cmp.ConfirmBehavior.Replace, select = false }),
                },
                sources = {{ name = 'ultisnips' }}
            }
    end
})
```

**Comment by smjonas** [comment]
Hey, I would really like to solve your issue. However, I just tested with your config and it works for me.

This is how it looks like when using your config with `vim-snippets` in a Java file and hitting `<C-space>`:
![#25](https://user-images.githubusercontent.com/40792180/143851521-c8635b84-5e4e-4a94-a694-53404dce1332.png)

Can you tell me the output of the following command?
```vim
:call UltiSnips#SnippetsInCurrentScope(1) | lua print(vim.inspect(vim.g.current_ulti_dict_info))

```

**Comment by rebelot** [comment]
this is the output of the command for a lua file (trying to complete date global snippet)

<img width="834" alt="Screenshot 2021-11-29 at 13 29 12" src="https://user-images.githubusercontent.com/36300441/143868272-81641edf-67f1-4ba9-9bee-c66055075979.png">

```vi
{
  ["#!"] = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:1"
  },
  AGPL = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:265"
  },
  AGPL3 = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:86"
  },
  APACHE = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:219"
  },
  BEERWARE = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:235"
  },
  BSD2 = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:112"
  },
  BSD3 = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:140"
  },
  BSD4 = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:167"
  },
  GMGPL = {
    description = "linking exception",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:103"
  },
  GPL2 = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:18"
  },
  GPL3 = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:52"
  },
  ISC = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:281"
  },
  LGPL2 = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:35"
  },
  LGPL3 = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:69"
  },
  MIT = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:197"
  },
  MPL2 = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:260"
  },
  WTFPL = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:244"
  },
  ["c)"] = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:4"
  },
  date = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:6"
  },
  datetime = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:14"
  },
  ddate = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:8"
  },
  diso = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:10"
  },
  elif = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:32"
  },
  for = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:10"
  },
  fori = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:18"
  },
  forp = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:14"
  },
  fun = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:6"
  },
  if = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:22"
  },
  ife = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:26"
  },
  im = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:45"
  },
  local = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:4"
  },
  lorem = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:16"
  },
  print = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:43"
  },
  repeat = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:35"
  },
  time = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/_.snippets:12"
  },
  while = {
    description = "",
    location = "/Users/laurenzi/.local/share/nvim/site/pack/packer/start/vim-snippets/snippets/lua.snippets:39"
  }
}
```

**Comment by smjonas** [comment]
Oh I think I know what's the issue. I was convinced that UltiSnips only supports snippets of the form `snippet ... ensnippet` as one would guess when reading the helpdocs. As can be seen here https://github.com/SirVer/ultisnips/blob/2c83e40ce66814bf813457bb58ea96184ab9bb81/doc/UltiSnips.txt#L1768, apparently UltiSnips also supports snippets using vsnip syntax. I will update the parser for this, thank you for providing the details! We will let you know once this has been fixed, thanks for your patience.

**Comment by rebelot** [comment]
thank you! but this raises another issue (for me...) why snippets are searched only in `vim-snippets/snippets` folder and not also in `vim-snippets/UltiSnips`?

**Comment by smjonas** [comment]
That's actually a really good question, the issues with the rtp just happened to me also. Packer actually has some problems with setting rtp, I will test your solution and probably update the readme once it works.

**Comment by smjonas** [comment]
@quangnguyen30192 I think we should not support `vim-snipmate`-like snippets at the moment. That would be quite a lot of work and involve a few edge cases. But we should update the readme again for `honza/vim-snippets` users.

**Comment by rebelot** [comment]
> Or maybe fallback to not using the custom parser if a snipmate snippet is found (then we will only have the tab_trigger and description info).

I second this... I find snipmate snippets very useful (like licenses, date, author/program info)

**Comment by smjonas** [comment]
While thinking about it, snipmate snippets only have a tab_trigger and description anyway (at least on the main branch). So there is no need to change the parser, we can simply use the info provided by UltiSnips.

**Comment by rebelot** [comment]
Not all of them are shown on latest (i.e. box (this one is super useful imo), bbox, docs, MIT, ...). I'm reverting and locking for now. Thanks for the support, hope you'll find a way to implement that!

**Comment by smjonas** [comment]
@rebelot I have updated the `snippets.lua` file and it seems to working now for vsnip snippets :) Will create a PR later and hopefully the issue will be resolved then.

**Comment by quangnguyen30192** [comment]
Thanks @smjonas for your effort

**Comment by smjonas** [comment]
@rebelot could you check if the new updates resolve your issue? We completely got rid of the custom parser now :D

**Comment by rebelot** [comment]
Everything seems to works nicely! Thank you very much!  👍
